### PR TITLE
Support multiple intervals

### PR DESCRIPTION
**Pull request by ekinhbayar**
Related to #1, not yet finished though

### CODE REVIEW

**Comment by memclutter** [comment]
Hello. In branch issue2-custom-separator i create class ParserSettings. It extends ArrayObjects. To resolve conflicts i need merge my branch into your multiple and send new pull request. In new pull request i add this new parser settings. 

Sorry for my english!

**Comment by ekinhbayar** [comment]
Hey, not a problem :) So, I think I should revert back your first merge and wait for a new one, am I right @memclutter ?

**Comment by memclutter** [comment]
Yes. I create pull request, but not see your pull request)

**Comment by ekinhbayar** [comment]
Alright, I reverted it back to original now

**Comment by memclutter** [comment]
ok. merge your multiple branch with master. And I create new branch for improve ParserSettings

**Comment by ekinhbayar** [comment]
Sorry for the wait, now merged this one :) @memclutter

**Pull request merged**
